behaviors:
  MotorcycleAI:
    trainer_type: ppo
    max_steps: 25000000 
    time_horizon: 256 
    summary_freq: 10000
    hyperparameters:
      batch_size: 1024
      buffer_size: 20480
      learning_rate: 1.0e-4
      learning_rate_schedule: linear  
      beta: 1.0e-3                    
      epsilon: 0.1
      lambd: 0.95
      num_epoch: 4
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0